### ISSUE TITLE
Not working for TI-84 Plus CE-T

### ISSUE THREAD

**Issue by PrivacyDragon** [Timendus/ticalc-usb#5] opened 2020-09-05 09:37 UTC
I have tried if it worked on a linux pc for the TI-84 Plus CE-T, because the TI-Connect software is not available for Linux.
But it didn't work.
So: On Linux, it doesn't work for the TI-84 Plus CE-T

**Comment by adriweb** [comment] 2020-09-05 12:39
Yes, the version used on the website currently doesn't have all the improvements made on the source code yet. Some PRs need to be merged etc first.

**Comment by PrivateDragon** [comment] 2020-09-05 13:50
I don't know if the problem is either in the website or because I use Linux. 
My laptop didn't recognize the calculator as a device...
I couldn't find it.
So maybe it's a problem with the communication between Linux and the TI-84 Plus CE-T?

**Comment by adriweb** [comment] 2020-09-05 13:52
No that's the thing - the current version is only going to work with the TI-84 Plus calculator, not the CE just yet. For that you'd have to "build" the latest sources (well from the PR)

**Comment by PrivateDragon** [comment] 2020-09-06 15:11
Is anyone going to do that in the near future?

**Comment by Jeffitus** [comment] 2020-09-06 16:52
Probably yes eventually; since you're on Linux I recommend installing TiLP. You can find info on installing it here: http://lpg.ticalc.org/prj_tilp/linux.html

**Comment by adriweb** [comment] 2020-09-06 16:53
(Or rather, for the latest version of the install script, here: https://raw.githubusercontent.com/debrouxl/tilp_and_gfm/master/tilp/trunk/build/scripts/install_tilp.sh)

**Comment by PrivateDragon** [comment] 2020-09-06 17:37
The problem with TiLP is that I have to ask my father to install it on my laptop, and when he looked at the dependencies he said that it might not work on my laptop because I have KDE instead of something else..?
And he doesn't really know how to get the latest version from Github.
(The version on github is very recently updated I think)

**Comment by adriweb** [comment] 2020-09-06 17:56
In the link I gave you, it has the dependencies listed. That will get&build the latest version from github.

**Comment by debrouxl** [comment] 2020-09-06 18:24
Timendus' readme for this repo lays out the steps you need to take to build it. I used them several weeks ago.

TILP is desktop-agnostic. It used to have an integration with KDE 3 file dialogs, but I removed that a while ago. I know that there's Trinity, but that's even far more of a dwarf in terms of real-world usage than KDE 5...

**Closed** 2020-11-29 12:29 UTC
Labels: device support request
